# Generated by Django 4.0.5 on 2022-06-01 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0002_freepost_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('freepost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hwapp.freepost')),
            ],
        ),
    ]
