# Generated by Django 4.0.5 on 2022-06-01 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0003_freecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freecomment',
            name='freepost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hwapp.freepost'),
        ),
    ]
