# Generated by Django 4.0.5 on 2022-06-01 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hwapp', '0004_alter_freecomment_freepost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freecomment',
            old_name='freepost',
            new_name='post',
        ),
    ]
